/** Aloa main entry point -- header file. 
 * @file
 * @mainpage
 *
 * <h1>ALOA -- A Lint Output Analyzer.</h1>
 *
 * ALOA is a freely available tool that processes output generated by PC-Lint
 * and computes various useful metrics.
 *
 * These metrics can be used to get a quick overview of the internal quality of
 * a C/C++ project. ALOA shows which kind of Lint issues are most frequently
 * encountered in a project and highlights issue-laden modules.
 *
 * ALOA’s metrics are useful for tracking changes of the Lint conformity between
 * builds and for fine-tuning a project’s Lint policy.
 *
 * ALOA is free software according to the GNU General Public License. You must read
 * and accept its terms before using ALOA.
 *
 * Copyright (c) 2006 - 2014 by Ralf Holly.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
